"""add user_id to tag table

Revision ID: a9a2e5eab193
Revises: 55168fd74afd
Create Date: 2025-11-03 07:40:35.948491

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9a2e5eab193"
down_revision: Union[str, Sequence[str], None] = "55168fd74afd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tag", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "tag", "user_account", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tag", type_="foreignkey")
    op.drop_column("tag", "user_id")
    # ### end Alembic commands ###
