"""add bio and avatar columns to user_account table

Revision ID: 647860766868
Revises: 
Create Date: 2025-11-02 18:27:58.904868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '647860766868'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('user_account', sa.Column('avatar', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'avatar')
    op.drop_column('user_account', 'bio')
    # ### end Alembic commands ###
